deps: ntlmclient: provide platform-independent htonll implementation
libgit2/libgit2 pull request #5614
Opened 2020-08-24 10:21 UTC by pks-t

With the introduction of ntlmclient, we've started playing whac-a-mole
with platforms to support the non-standard htonll function. Let's end
this game once and for all by providing a generic implementation that's
implemented via htonl(3P) and a endianness-check in CMake.

2020-08-24 10:22 UTC, pks-t commented
/cc @ethomson

2020-08-24 13:01 UTC, ethomson approved these changes

2020-08-24 15:06 UTC, ryandesign commented
Could this be done without requiring the endianness to be detected in the cmake script, but rather detecting it at build time in compat.h using preprocessor defines that are provided by the compiler? On some platforms like macOS it is possible to build for multiple architectures simultaneously (e.g. `cc -arch i386 -arch x86_64 -arch ppc ...`) in which case it is not possible to know at cmake time what the endianness or bitness will be at build time.

2020-08-24 15:16 UTC, ryandesign commented
For example, `__BIG_ENDIAN__ ` or `__LITTLE_ENDIAN__` is defined by macOS compilers so this should work on macOS:

```
#ifdef __BIG_ENDIAN__
static inline uint64_t ntlm_htonll(uint64_t value)
{
	return value;
}
#else

# include <arpa/inet.h>

static inline uint64_t ntlm_htonll(uint64_t value)
{
	return ((uint64_t)htonl(value) << 32) + htonl((uint64_t)value >> 32);
}

#endif
```

I don't know what defines other systems use.

2020-08-25 13:21 UTC, ethomson commented
> On some platforms like macOS it is possible to build for multiple architectures simultaneously (e.g. cc -arch i386 -arch x86_64 -arch ppc ...) in which case it is not possible to know at cmake time what the endianness or bitness will be at build time.

This isn't something that we support out-of-the-box already.  Our cmake recipes determine the bitness of the machine, so you couldn't `-arch i386 -arch x86_64`.  Supporting this seems like a reasonable goal but I don't think that we should block this on that.  We'd probably just want to do the quadfat magic ourselves with `lipo` 🤷‍♂️ .

2020-08-25 13:23 UTC, ethomson commented
Although having said that, we do need to let people who build without CMake deal with this properly.  

We have a pattern for the libgit2 defines (like `GIT_ARCH_64`) in `features.h`, but we don't have any pattern for the NTLM dependency.  ☹️

2020-08-26 14:31 UTC, ryandesign commented
> so you couldn't `-arch i386 -arch x86_64`.

Building with `-arch i386 -arch x86_64` does succeed, but it is certainly possible that what gets built that way doesn't work correctly.

> Supporting this seems like a reasonable goal but I don't think that we should block this on that. We'd probably just want to do the quadfat magic ourselves with `lipo`

You probably don't want to add any code to do multi-architecture builds. It's fine to leave that up to the users who want to do it. For the sake of MacPorts, I'll switch our libgit2 build over to the build-multiple-times-and-lipo approach.

2020-08-31 11:43 UTC, ethomson commented
> Building with -arch i386 -arch x86_64 does succeed, but it is certainly possible that what gets built that way doesn't work correctly.

Interesting.  I'll have to do a little investigation here.  I suspect that - assuming that you're doing the build on amd64 (which I certainly hope is true 😁) that the i386 version may have some issues.  I'll have to 👀

2020-08-31 11:44 UTC, ethomson requested changes
We'll need to add this to `config.h.in` to support non-CMake users.

2020-10-14 11:31 UTC, ethomson commented
Fixed with #5658 which won't require any changes to `config.h.in` or require non-CMake users to make any changes.

2020-10-14 11:31 UTC, closed without merging