Use environment variables when creating signatures
libgit2/libgit2 pull request #6706
Opened 2023-12-21 21:58 UTC by u-quark

When creating an action signature (e.g. for a commit author and committer) read the following environment variables that can override the configuration options:

 * `GIT_AUTHOR_NAME` is the human-readable name in the "author" field.
 * `GIT_AUTHOR_EMAIL` is the email for the "author" field.
 * `GIT_AUTHOR_DATE` is the timestamp used for the "author" field.
 * `GIT_COMMITTER_NAME` sets the human name for the "committer" field.
 * `GIT_COMMITTER_EMAIL` is the email address for the "committer" field.
 * `GIT_COMMITTER_DATE` is used for the timestamp in the "committer" field.
 * `EMAIL` is the fallback email address in case the user.email configuration value isn't set. If this isn't set, Git falls back to the system user and host names.

This is taken from the git documentation chapter "10.8 Environment Variables":

https://git-scm.com/book/en/v2/Git-Internals-Environment-Variables

This PR adds support for reading these environment variables by adding two new functions `git_signature_default_author` and `git_signature_default_committer` and deprecates the `git_signature_default` function.

Fixes: https://github.com/libgit2/libgit2/issues/3751

Prior work:
 * https://github.com/libgit2/libgit2/pull/4409
 * https://github.com/libgit2/libgit2/pull/5479
 * https://github.com/libgit2/libgit2/pull/6290

2023-12-22 10:20 UTC, ethomson commented
Thank you for the PR - I agree that we need this functionality. I took a quick first pass on the changes and overall, this is an excellent PR. I will take a closer look 🔜 — thanks again.

2023-12-24 10:05 UTC, u-quark commented
Hi, thanks for looking into this!

I am also keen on getting this functionality merged! Please let me know if you want a different approach of some specific implementation on this PR, I don't mind changing it.

I am not sure I recreated 100% the CI build environment but I managed to compile with clang with similar features enabled on cmake so hopefully this time CI will pass.

Cheers.

2024-01-14 00:43 UTC, ethomson requested changes

2024-01-14 00:43 UTC, ethomson commented
A few minor tweaks requested - thanks for putting this together, I think that this is a really useful improvement. 🙏

2024-01-14 12:28 UTC, u-quark commented
Thanks of the review @ethomson!

2024-02-24 14:35 UTC, csware commented
The usage of environment variables should always be opt-in in libgit2

2024-06-14 13:16 UTC, ethomson commented
Sorry, I've been slow to look at this. One of the things that I've found is that if you want to emulate `git commit` (for example), then you really want to a) look at the environment variables, but b) fall back to the _same time_ for both author and committer if you're using the current timestamp. I think that this needs to be a single API to get both instead of individual APIs.

Per @csware 's comment, I also think that switching all the behavior of the things that produce commits internally to look at the environment variables is a Big Change that would be unexpected in a small release. I would suggest that we keep the current behavior (wherein it does not honor the `GIT_AUTHOR_` and `GIT_COMMITTER_` environment variables for now. We can potentially make this opt-in (you can imagine a rebase option that says that it should honor the environment variable). We could also change the behavior of libgit2 to start paying attention to environment variables by default in a future release, with an explicit opt-out. But for now, I think that it needs to remain opt-in.

I'm going to push up a commit to this based on this to adjust...

2024-06-17 22:17 UTC, u-quark commented
Thanks for looking at this @ethomson, I've also been busy and didn't chase this.

I understand your points and they make sense! Both changes LGTM. I will have a closer look later this week and we should be able to merge this.

2024-06-18 19:48 UTC, ethomson commented
Thanks - sorry to bring the chaotic energy and just push a commit on top of your branch. I appreciate you opening this PR and apologize again for the delay.

2024-07-10 07:31 UTC, ethomson commented
Thanks again for the PR!

2024-07-10 07:31 UTC, merged

2024-07-24 12:52 UTC, u-quark commented
I just had some time to look into this. This is great! Works for me like a charm!

Thanks for merging this and sorry again for the late response.