Troubleshooting Steps
libgit2/libgit2 pull request #6719
Opened 2024-01-17 15:47 UTC by ChudeObiamaka

This error is raised because the pkg-config is not available in your system
Steps to resolve the problem
Install PkgConfig using the package manager
sudo apt-get update
sudo apt-get install pkg-config
PkgConfig tells the compiler where to find dependent libraries. Installing it with apt-get usually resolves the issue.

If GSSAPI is missing, Install the GSSAPI development package
sudo apt-get update
sudo apt-get install libkrb5-dev
If the issue persists, ensure that the GSSAPI libraries and include files are in standard locations. You can check their locations using
dpkg -L libgssapi-dev
Make sure that the paths are included in the compiler and linker search paths

If OpenSSL is missing, Install the OpenSSL development package
sudo apt-get update
sudo apt-get install libssl-dev
Installing libssl-dev provides the required OpenSSL libraries and headers.
You may also need to set the OpenSSL root directory path as a CMake variable. For example
cmake -DOPENSSL_ROOT_DIR=/usr/lib/ssl ..
Ensure to include any other details about the error messages in the documentation along with these troubleshooting steps. Let me know if you need any clarification or have additional questions!

2024-01-19 11:31 UTC, ChudeObiamaka commented
Please review my PR @naty55

2024-01-24 20:46 UTC, naty55 requested changes
Hi @ChudeObiamaka 
I guess I don't have the permissions to approve and merge PRs, Anyway it looks great to me but I'd add some styling for the `commands/code` blocks (md format lets you do it quite easily)

2024-01-24 20:50 UTC, naty55 commented
fixes #6640

2024-03-08 14:27 UTC, ethomson commented
Hi - if you're interested in pushing this forward, please don't remove things like headers, etc, or formatting.

2024-04-01 23:28 UTC, closed without merging